apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx
      version: v0.3.5
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: docker.io/nginxinc/nginx-unprivileged:latest
        name: nginx
        ports:
        - containerPort: 8080
