apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels: {{ toYaml .Values.labels | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
      - image: docker.io/nginxinc/nginx-unprivileged:latest
        name: nginx-test
        ports:
        - containerPort: 8080
